version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    target-branch: "main"
    reviewers:
      - "tetri"
    assignees:
      - "tetri"
    labels:
      - "dependencies"
      - "automated"
      - "nuget"
    commit-message:
      prefix: "chore"               
      include: "scope"
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
        versions: ["*"]
